export const emojiCatalog = {
  Faces: [
    "😀",
    "😃",
    "😄",
    "😁",
    "😆",
    "😅",
    "😂",
    "🤣",
    "☺️",
    "😊",
    "😇",
    "🙂",
    "🙃",
    "😉",
    "😌",
    "😍",
    "😘",
    "😗",
    "😙",
    "😚",
    "😋",
    "😛",
    "😝",
    "🤑",
    "🤗",
  ],
  Objects: ["💯", "🔥", "💥", "💢", "💦", "💫"],
  Places: ["🏠", "🏡", "🏢", "🏣", "🏥"],
  Animals: ["🐶", "🐱", "🐭", "🐹", "🐰", "🦊", "🐻", "🐼", "🐨", "🐯"],
  Custom: [
    "<img src='https://static-cdn.jtvnw.net/emoticons/v2/304420818/default/light/1.0' />",
    "<img src='https://static-cdn.jtvnw.net/emoticons/v2/25/default/light/1.0' />",
    "<img src='https://static-cdn.jtvnw.net/emoticons/v2/301056197/default/light/1.0' />",
    "<img src='https://static-cdn.jtvnw.net/emoticons/v2/emotesv2_18d8acf3364041edb8b4038d9d0f224f/default/light/1.0' />",
  ],
};
